Fix image-bottom-padding bug without display:block
koala-framework/koala-framework pull request #1086
Opened 2021-03-03 11:46 UTC by Ben-Ho

display:block does not allow easy center image.
display:inline-block + vertical-align:top does also solve image
padding-bottom problem but also allows centering image

2021-03-03 12:04 UTC, mariokemetinger approved these changes

2021-03-03 12:10 UTC, jamesricky commented
Kann man nicht einfach die Komponente mit einem `div` oder `td` wrappen und damit zentrieren?  
So ändert das hald das Styling von allen bestehenden NL's wo das in Verwendung ist...

2021-03-03 12:16 UTC, jamesricky requested changes
Kann man nicht einfach die Komponente mit einem div oder td wrappen und damit zentrieren?
So ändert das hald das Styling von allen bestehenden NL's wo das in Verwendung ist...

2021-03-03 12:21 UTC, Ben-Ho commented
> Kann man nicht einfach die Komponente mit einem div oder td wrappen und damit zentrieren?
> So ändert das hald das Styling von allen bestehenden NL's wo das in Verwendung ist...

also es wäre ja sogar von einen a tag gewrappt. aber das hatte leider keine auswirkung...  aber ich werd nochmal probieren... wie kann ich denn das display:block eines child aushebeln?

2021-03-03 12:23 UTC, Ben-Ho commented
> Kann man nicht einfach die Komponente mit einem div oder td wrappen und damit zentrieren?
> So ändert das hald das Styling von allen bestehenden NL's wo das in Verwendung ist...

btw. bestehend ist relativ. das ist ein change für 5.3. im worst-case markieren wir das im changelog als "inkompatibel"...

2021-03-03 12:27 UTC, Ben-Ho commented
> Kann man nicht einfach die Komponente mit einem div oder td wrappen und damit zentrieren?
> So ändert das hald das Styling von allen bestehenden NL's wo das in Verwendung ist...

wrappen funktioniert. whs ist das dann die bessere lösung. da ja auch das text-bild definiert, dass es zentriert ist. und das display:block ist ja nicht schlechter verwertbar/anpassbar als ein display:inline-block, oder?

2021-03-03 12:32 UTC, Ben-Ho commented
alternative lösung: https://github.com/koala-framework/koala-framework/pull/1087

2021-03-04 08:53 UTC, jamesricky commented
> alternative lösung: #1087

Die find ich gut 🙂

2021-04-07 05:24 UTC, kaufmo commented
@Ben-Ho kann der geclosed werden?

2022-04-07 04:23 UTC, closed without merging